- name: "Create kubernetes folders"
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    mode: 0640
    owner: root
    group: root

- name: "Push Kubernetes Master PKI files to master replicas"
  copy: 
    src: /tmp/kubeadm-ha/
    dest: /etc/kubernetes/
    owner: root
    group: root
    mode: preserve

- name : Generate master token
  shell : kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{groups['k8s_master_primary'][0]}}"



- set_fact:
    kubeadm_join: "{{kubeadm_join_cmd.stdout}}"
    when: not kubeadm_ca_slave.stat.exists

- name: Display the kubeadm_join result
  debug:
    var: kubeadm_join
    
- name: Join master replicas to cluster
  shell: "{{kubeadm_join}} --control-plane"



